artikel/urls.py
from django.conf.urls import url
from . views import (
                        IndexView,
                        CreateView,
                        UpdateView,
                        DeleteView,
                    )

urlpatterns = [
    url(r"^update/(?P<pk>\d+)$",UpdateView.as_view(), name="update"),
    url(r"^delete/(?P<pk>\d+)$",DeleteView.as_view(), name="delete"),
    url(r"^add/$",CreateView.as_view(), name="add"),
    url(r'^(?P<page>\d+)$', IndexView.as_view(), name='index'),
]

blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from . views import BlogHomeView, BlogDashboardView, LoginFormView
from artikel.views import (
                            ArtikelDetailView,ArtikelKategoriListView,ArtikelListView,
                            )

from django.urls import reverse_lazy
from django.contrib.auth.views import(
    LoginView,
    LogoutView,
)

urlpatterns = [
    url(r'^dashboard/artikel/', include("artikel.urls",namespace="dashboard_artikel")),
    url(r'^dashboard/', BlogDashboardView.as_view(), name='dashboard'),
    url(r'^login/$', LoginFormView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^kategori/(?P<category>[\w\s]+)$', ArtikelKategoriListView.as_view(), name='category'),
    url(r'^detail/(?P<slug>[\w-]+)$', ArtikelDetailView.as_view(), name='detail'),
    url(r'^(?P<page>\d+)$', ArtikelListView.as_view(), name='list'),
    url(r'^$', BlogHomeView.as_view(), name='home'),
]

artikel/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class Artikel(models.Model):
    judul       = models.CharField(max_length=255)
    isi         = models.TextField()
    kategori    = models.CharField(max_length=255)
    published   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    slug        = models.SlugField(blank=True,editable=False)
    
    def save(self):
        self.slug = slugify(self.judul)
        super().save()
    
    def get_absolute_url(self):
        return reverse("dashboard_artikel:index", kwargs={"page":1})
    
    def __str__(self):
        return "{}.{}".format(self.id, self.judul)

artikel/forms.py
from django.forms import ModelForm

from .models import Artikel

class ArtikelForm(ModelForm):
    class Meta:
        model = Artikel
        fields = [
            'judul',
            'isi',
            'kategori',
        ]

artikel/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,DeleteView,UpdateView
from django.urls import reverse_lazy
from . models import Artikel
from . forms import ArtikelForm

class IndexView(ListView):
    model = Artikel
    template_name = "artikel/index.html"
    ordering = ['-published']
    paginate_by = 5

class CreateView(CreateView):
    form_class = ArtikelForm
    template_name = "artikel/create.html"

class UpdateView(UpdateView):
    form_class = ArtikelForm
    model = Artikel
    template_name = "artikel/update.html"

class DeleteView(DeleteView):
    model = Artikel
    template_name = "artikel/delete.html"
    success_url = reverse_lazy("dashboard_artikel:index",kwargs={"page":1})


  
# for home
class ArtikelForHome():
    model = Artikel
    def get_all_artikel(self):
        artikel_list = self.model.objects.all().order_by('-published')
        return artikel_list
    
    def get_latest_artikel_each_category(self):
        kategori_list = self.model.objects.values_list('kategori',flat=True).distinct()
        artikel_list = []
        
        for kategori in kategori_list:
            artikel = self.model.objects.filter(kategori=kategori).latest('published')
            artikel_list.append(artikel)
            
        return artikel_list
 
class ArtikelKategoriListView(ListView):
    model = Artikel
    template_name = "kategori_list.html"
    context_object_name = "artikel_list"
    ordering = ['-published']
    paginate_by = 5
    
    def get_queryset(self):
        self.queryset = self.model.objects.filter(kategori=self.kwargs['category'])
        return super().get_queryset()
    
    def get_context_data(self,*args, **kwargs):
        kategori_list = self.model.objects.values_list('kategori',flat=True).distinct().exclude(kategori=self.kwargs['category'])
        self.kwargs.update({'kategori_list':kategori_list,
                            'heading_kategori':self.kwargs['category'],
                            })
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)
    
class ArtikelListView(ListView):
    model = Artikel
    template_name = "list.html"
    context_object_name = "artikel_list"
    ordering = ['-published']
    paginate_by = 5
    
    def get_context_data(self,*args, **kwargs):
        kategori_list = self.model.objects.values_list('kategori',flat=True).distinct()
        self.kwargs.update({'kategori_list':kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)
    
class ArtikelDetailView(DetailView):
    model = Artikel
    template_name = "detail.html"
    context_object_name = "artikel"

    def artikel_sebelum_sesudah(self):
        artikel_semua=  list(self.model.objects.values_list('slug',flat=True).order_by('-published'))
        artikel_saat_ini =  artikel_semua.index(self.kwargs['slug'])
        if artikel_saat_ini<len(artikel_semua):
            if artikel_saat_ini==0:
                artikel_sebelumnya = artikel_semua[artikel_saat_ini+1]
                artikel_berikutnya = None
            elif artikel_saat_ini==len(artikel_semua)-1:
                artikel_sebelumnya = None
                artikel_berikutnya = artikel_semua[artikel_saat_ini-1]
            else:
                artikel_sebelumnya = artikel_semua[artikel_saat_ini+1]
                artikel_berikutnya = artikel_semua[artikel_saat_ini-1]
              
        hasil = {"next":artikel_berikutnya,"previous":artikel_sebelumnya}
        return hasil
    
    def get_context_data(self,*args, **kwargs):
        artikel_serupa = self.model.objects.filter(kategori=self.object.kategori).exclude(slug=self.kwargs['slug'])
        kategori_list = self.model.objects.values_list('kategori',flat=True).distinct().exclude(kategori=self.object.kategori)
        self.kwargs.update({'artikel_serupa':artikel_serupa,
                            'kategori_list':kategori_list,
                            'next':self.artikel_sebelum_sesudah()['next'],
                            'previous':self.artikel_sebelum_sesudah()['previous'],
                            })
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)
        

blog/views.py
from django.views.generic import TemplateView
from artikel.views import ArtikelForHome
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import(
    LoginView,
    LogoutView,
)

class BlogHomeView(TemplateView,ArtikelForHome):
    template_name = "index.html"
    
    def get_context_data(self):
        context  =   {
                        'artikel_all_list':self.get_all_artikel(),
                        'artikel_each_category_list':self.get_latest_artikel_each_category(),
                        
                    }
        return context
    
class BlogDashboardView(LoginRequiredMixin,TemplateView):
    template_name = "index_admin.html"

class LoginFormView(SuccessMessageMixin, LoginView):
    template_name = 'login.html'
    success_url = '/dashboard'
    success_message = "You were successfully logged in"

    

artikel/templates/artikel/create.html
{% extends 'layout/backend/base.html' %}


{% block contents %}
  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">Manajemen Artikel</h1>

  <div class="row">

    <div class="col-lg-6">
      <!-- Circle Buttons -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Tambah Artikel</h6>
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            
            <div class="form-group">
              <label for="{{form.judul.id_for_label}}">{{form.judul.label}}</label>
              <input class="form-control" type="text" name="{{form.judul.name}}" maxlength="{{form.judul.max}}" id="{{form.judul.id_for_label}}" required>
            </div>
            <div class="form-group">
              <label for="{{form.isi.id_for_label}}">{{form.isi.label}}</label>
              <textarea class="form-control" name="{{form.isi.name}}" id="{{form.judul.id_for_label}}" cols="30" rows="10" required></textarea>
            </div>
            <div class="form-group">
              <label for="{{form.kategori.id_for_label}}">{{form.kategori.label}}</label>
              <input class="form-control" type="text" name="{{form.kategori.name}}" maxlength="{{form.kategori.max}}" id="{{form.kategori.id_for_label}}" required>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>

  </div>
{% endblock contents %}
  

artikel/templates/artikel/delete.html
{% extends 'layout/backend/base.html' %}


{% block contents %}
<!-- Page Heading -->
<h1 class="h3 mb-4 text-gray-800">Manajemen Artikel</h1>
<div class="row">

        <div class="col-lg-6">
          <!-- Circle Buttons -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Konfirmasi Hapus</h6>
            </div>
            <div class="card-body">
                <p>Apakah Anda Akan Menghapus Artikel</p>
                <h3>{{object.judul}}</h3>
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-check"></i>
                        </span>
                        <span class="text">Ya</span>
                    </button>
                    <a href="{% url 'dashboard_artikel:index' 1  %}" class="btn btn-primary btn-icon-split">
                        <span class="icon text-white-50">
                            <i class="fas fa-times"></i>
                        </span>
                        <span class="text">Tidak</span>
                    </a>
                </form>
            </div>
          </div>
        </div>
    
      </div>


{% endblock contents %}

artikel/templates/artikel/index.html
{% extends 'layout/backend/base.html' %}


{% block contents %}
  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">Manajemen Artikel</h1>

  <div class="row">

    <div class="col-lg-8">
      <!-- Circle Buttons -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Artikel</h6>
        </div>
        <div class="card-body">
            <a href="{% url 'dashboard_artikel:add'  %}"  class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-plus"></i>
                </span>
                <span class="text">Tambah</span>
            </a>
            <div class="my-2"></div>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Judul</th>
                    <th scope="col">Kategori</th>
                    <th scope="col" colspan="2">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for artikel in object_list  %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{artikel.judul}}</td>
                            <td>{{artikel.kategori}}</td>
                            <td>
                                <a href="{% url 'dashboard_artikel:update' artikel.id  %}" class="btn btn-primary btn-circle">
                                    <i class="fas fa-edit"></i>
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'dashboard_artikel:delete' artikel.id  %}" class="btn btn-danger btn-circle">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr>
            <nav aria-label="Page navigation example">
                <!-- Pagination -->
                {% if is_paginated %}
                <ul class="pagination justify-content-center mb-4">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'dashboard_artikel:index' page_obj.previous_page_number  %}">&larr; Terbaru</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#">&larr; Terbaru</a>
                            </li>
                        {% endif %}
                        
                        
                        {% for page in paginator.page_range  %}
                            {% if page is page_obj.number %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" href="#">{{page}}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'dashboard_artikel:index' page  %}">{{page}}</a>
                                </li>
                            {% endif %}
                                
                        {% endfor %}
                            
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'dashboard_artikel:index' page_obj.next_page_number  %}">Sebelumnya &rarr;</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#">Sebelumnya &rarr;</a>
                            </li>
                        {% endif %}
                </ul>
                {% endif %}
            </nav>
        </div>
      </div>
    </div>

  </div>
{% endblock contents %}
  

artikel/templates/artikel/update.html
{% extends 'layout/backend/base.html' %}


{% block contents %}
  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">Manajemen Artikel</h1>

  <div class="row">

    <div class="col-lg-10">
      <!-- Circle Buttons -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Update Artikel</h6>
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            
            <div class="form-group">
              <label for="{{form.judul.id_for_label}}">{{form.judul.label}}</label>
              <input class="form-control" type="text" name="{{form.judul.name}}" maxlength="{{form.judul.max}}" id="{{form.judul.id_for_label}}" value="{{form.judul.value}}" required>
            </div>
            <div class="form-group">
              <label for="{{form.isi.id_for_label}}">{{form.isi.label}}</label>
              <textarea class="form-control" name="{{form.isi.name}}" id="{{form.judul.id_for_label}}" cols="30" rows="10" required>{{form.isi.value}}</textarea>
            </div>
            <div class="form-group">
              <label for="{{form.kategori.id_for_label}}">{{form.kategori.label}}</label>
              <input class="form-control" type="text" name="{{form.kategori.name}}" maxlength="{{form.kategori.max}}" id="{{form.kategori.id_for_label}}" value="{{form.kategori.value}}" required>
            </div>
            <button type="submit" class="btn btn-warning">Update</button>
            <a href="{% url 'dashboard_artikel:index' 1  %}" class="btn btn-success">Batal</a>
          </form>
        </div>
      </div>
    </div>

  </div>
{% endblock contents %}
  

templates/detail.html
{% extends 'layout/frontend/base.html' %}


{% block contents %}
<div class="col-md-8">
    <h1 class="my-4">
        {{artikel.judul}}
    </h1>
     <!-- Blog Post -->


    <div class="card mb-4">
            <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{artikel.isi}}</p>
            </div>
            <div class="card-footer text-muted">
                Diposting {{artikel.published}} dalam Kategori
                <a href="#">{{artikel.kategori}}</a>
            </div>
    </div>

    <ul class="pagination justify-content-center mb-4">
        
        {% if next != None %}
            <li class="page-item">
                <a class="page-link" href="{% url 'detail' next  %}">&larr; Baru</a>
            </li>
        {% endif %}
        {% if previous != None %}
            <li class="page-item ">
                <a class="page-link" href="{% url 'detail' previous  %}">Lama &rarr;</a>
            </li>
        {% endif %}
        
        
    </ul>
</div> 
{% include 'layout/frontend/snippets/sidebar.html' %}
{% endblock contents %}
    

templates/index.html
{% extends 'layout/frontend/base.html' %}

{% block title %}
      Blog Home - Start Bootstrap Template
{% endblock title %}

{% block contents %}
      <div class="col-md-12">
            <h1 class="my-4">
                  Artikel <small>Terbaru</small>
            </h1>
            <div class="row" >
                  {% for artikel in artikel_all_list  %}
                        {% if forloop.counter < 9 %}
                              <div class="col-md-3">
                                    <div class="card my-4">
                                          <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                                          <div class="card-body">
                                                <h5 class="card-title">{{artikel.judul}}</h5>
                                                <a href="{% url 'detail' artikel.slug %}"  class="btn btn-primary">Read More &rarr;</a>
                                          </div>
                                          <div class="card-footer text-muted">
                                                {{artikel.published|date}}
                                          </div>
                                    </div>
                              </div>
                        {% endif %}
                  {% endfor %}
            </div>
            <ul class="pagination justify-content-center mb-4">
                  <li class="page-item">
                        <a class="btn btn-dark" href="{% url 'list' 1  %}">Selengkapnya</a>
                  </li>
            </ul>
      </div>
      
      <div class="col-md-12">
                  <h1 class="my-4">
                        Artikel <small>Kategori</small>
                  </h1>
                  <div class="row">
                        {% for artikel in artikel_each_category_list  %}
                              {% if forloop.counter < 9 %}
                                    <div class="col-md-3">
                                          <div class="card my-4">
                                                <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                                                <div class="card-body">
                                                      <h5 class="card-title">{{artikel.kategori}}</h5>
                                                      <a href="{% url 'category' artikel.kategori %}"  class="btn btn-primary">Read More &rarr;</a>
                                                </div>
                                          </div>
                                    </div>
                              {% endif %}
                        {% endfor %}
                  </div>
            </div>
{% endblock contents %}
    

templates/kategori_list.html
{% extends 'layout/frontend/base.html' %}


{% block contents %}
<div class="col-md-8">
    <h1 class="my-4">
        Artikel <small>{{heading_kategori}}</small>
    </h1>
     <!-- Blog Post -->
    {% for artikel in artikel_list  %}

        <div class="card mb-4">
                <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                <div class="card-body">
                    <h2 class="card-title">{{artikel.judul}}</h2>
                    <p class="card-text">{{artikel.isi|truncatewords:50}}</p>
                    <a href="{% url 'detail' artikel.slug %}"  class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                    Diposting {{artikel.published}} dalam Kategori
                    <a href="{% url 'category' artikel.kategori %}">{{artikel.kategori}}</a>
                </div>
        </div>
    {% endfor %}

    <!-- Pagination -->
    {% if is_paginated %}
        <ul class="pagination justify-content-center mb-4">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'list' page_obj.previous_page_number  %}">&larr; Terbaru</a>
                     </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">&larr; Terbaru</a>
                    </li>
                {% endif %}
                
                
                {% for page in paginator.page_range  %}
                    {% if page is page_obj.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">{{page}}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'list' page  %}">{{page}}</a>
                        </li>
                    {% endif %}
                        
                {% endfor %}
                    
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'list' page_obj.next_page_number  %}">Sebelumnya &rarr;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Sebelumnya &rarr;</a>
                    </li>
                {% endif %}
        </ul>
    {% endif %}
</div>
{% include 'layout/frontend/snippets/sidebar.html' %}
{% endblock contents %}


    

templates/layout/backend/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Dashboard</title>

  {% include 'layout/backend/snippets/styles.html' %}

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include 'layout/backend/snippets/sidebar.html' %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include 'layout/backend/snippets/topbar.html' %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          {% block contents %}
            
          {% endblock contents %}
  
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      {% include 'layout/backend/snippets/footer.html' %}
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Modal-->
  {% include 'layout/backend/snippets/modal.html' %}

  {% include 'layout/backend/snippets/scripts.html' %}
</body>

</html>

templates/layout/backend/snippets/footer.html
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
      <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Website 2019</span>
      </div>
    </div>
</footer>
<!-- End of Footer -->

templates/layout/backend/snippets/modal.html
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
        </div>
      </div>
    </div>
</div>

templates/layout/backend/snippets/scripts.html
{% load static %}
<!-- Bootstrap core JavaScript-->
<script src="{% static 'backend/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'backend/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'backend/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'backend/js/sb-admin-2.min.js' %}"></script>

<!-- Page level plugins -->
<script src="{% static 'backend/vendor/chart.js/Chart.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'backend/js/demo/chart-area-demo.js' %}"></script>
<script src="{% static 'backend/js/demo/chart-pie-demo.js' %}"></script>

templates/layout/backend/snippets/sidebar.html
 <!-- Sidebar -->
 <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
      <a class="nav-link" href="index.html">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Interface
    </div>
    
    <!-- Nav Item - Charts -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'dashboard_artikel:index' 1 %}" >
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Artikel</span></a>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <!-- <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
        <i class="fas fa-fw fa-cog"></i>
        <span>Components</span>
      </a>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Custom Components:</h6>
          <a class="collapse-item" href="buttons.html">Buttons</a>
          <a class="collapse-item" href="cards.html">Cards</a>
        </div>
      </div>
    </li> -->

    <!-- Nav Item - Utilities Collapse Menu -->
    <!-- <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
        <i class="fas fa-fw fa-wrench"></i>
        <span>Utilities</span>
      </a>
      <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Custom Utilities:</h6>
          <a class="collapse-item" href="utilities-color.html">Colors</a>
          <a class="collapse-item" href="utilities-border.html">Borders</a>
          <a class="collapse-item" href="utilities-animation.html">Animations</a>
          <a class="collapse-item" href="utilities-other.html">Other</a>
        </div>
      </div>
    </li> -->

    <!-- Divider -->
    <!-- <hr class="sidebar-divider"> -->

    <!-- Heading -->
    <!-- <div class="sidebar-heading">
      Addons
    </div> -->

    <!-- Nav Item - Pages Collapse Menu -->
    <!-- <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
        <i class="fas fa-fw fa-folder"></i>
        <span>Pages</span>
      </a>
      <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Login Screens:</h6>
          <a class="collapse-item" href="login.html">Login</a>
          <a class="collapse-item" href="register.html">Register</a>
          <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
          <div class="collapse-divider"></div>
          <h6 class="collapse-header">Other Pages:</h6>
          <a class="collapse-item" href="404.html">404 Page</a>
          <a class="collapse-item" href="blank.html">Blank Page</a>
        </div>
      </div>
    </li> -->


    <!-- Nav Item - Tables -->
    <!-- <li class="nav-item">
      <a class="nav-link" href="tables.html">
        <i class="fas fa-fw fa-table"></i>
        <span>Tables</span></a>
    </li> -->

    <!-- Divider -->
    <!-- <hr class="sidebar-divider d-none d-md-block"> -->

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

  </ul>
  <!-- End of Sidebar -->